=== QuocHuyTruong/XML/vd4-c3.dtd
<!ELEMENT OrderDetail (OrderDate, Customer, Item1, Item2)*>
<!ELEMENT OrderDate (#PCDATA)>
<!ELEMENT Customer (#PCDATA)>
<!ELEMENT Item1 (ProductID, Quantity) >
<!ELEMENT Item2 (ProductID, Quantity) >
<!ELEMENT ProductID (#PCDATA)>
<!ELEMENT Quantity (#PCDATA)>

=== QuocHuyTruong/XML/vd4-c3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE OrderDetail SYSTEM "file:/D:/XML/vd4-c3.dtd">
<?xml-stylesheet type="text/css" href="cd_catalog.css"?>
<OrderDetail>
    <OrderDate>2006-6-6</OrderDate>
    <Customer>anhphi</Customer>
    <Item1>
        <ProductID>3</ProductID>
        <Quantity>3</Quantity>
    </Item1>
    <Item2>
        <ProductID>1</ProductID>
        <Quantity>5</Quantity>
    </Item2>
</OrderDetail>
