=== QuocHuyTruong/XML/vd7-c3.dtd
<!ELEMENT DatHang (NgayDat, KhachHang, SanPham*)*>
<!ELEMENT SanPham (MaSo, SoLuong)>
<!ELEMENT MaSo (#PCDATA)>
<!ELEMENT SoLuong (#PCDATA)>
<!ELEMENT NgayDat (#PCDATA)>
<!ELEMENT KhachHang (#PCDATA)>

=== QuocHuyTruong/XML/vd7-c3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE DatHang SYSTEM "file:/D:/XML/vd7-c3.dtd">
<DatHang>
    <NgayDat>27-2-2003</NgayDat>
    <KhachHang>tran thanh nhan</KhachHang>
    <SanPham>
        <MaSo>5</MaSo>
        <SoLuong>7</SoLuong>
    </SanPham>
    <SanPham>
        <MaSo>1</MaSo>
        <SoLuong>9</SoLuong>
    </SanPham>
</DatHang>
