=== QuocHuyTruong/XML/TruongQuocHuy_KTlan2_61133757/QLNH.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xs:element name="QLNH">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="NhanVien" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="MaNV">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="NV[0-9]{2}"></xs:pattern>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="HoLot" type="xs:string"/>
                            <xs:element name="Ten" type="xs:string" />
                            <xs:element name="GioiTinh">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="Nam|Nu"></xs:pattern>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="HangHoa" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="MaHH">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="H[0-9]{3}"></xs:pattern>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="TenHH" type="xs:string"/>
                            <xs:element name="DonViTinh" type="xs:string"/>
                            <xs:element name="TenNCC" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="HoaDonNhap" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="SoHD">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="HD[0-9]{4}"></xs:pattern>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="NgayNhap" type="xs:string"/>
                            <xs:element name="MaNV" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="ChiTietNhap" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="SoHD" type="xs:string"/>
                            <xs:element name="MaHH" type="xs:string"/>
                            <xs:element name="SoLuong" type="xs:int"/>
                            <xs:element name="DonGiaNhap">
                                <xs:simpleType>
                                    <xs:restriction base="xs:float">
                                        <xs:minInclusive value="0"></xs:minInclusive>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
        <xs:key name="NhanVienKey">
            <xs:selector xpath="NhanVien"/>
            <xs:field xpath="MaNV"/>
        </xs:key>
        <xs:key name="HangHoaKey">
            <xs:selector xpath="HangHoa"/>
            <xs:field xpath="MaHH"/>
        </xs:key>
        <xs:key name="HoaDonNhapKey">
            <xs:selector xpath="HoaDonNhap"/>
            <xs:field xpath="SoHD"/>
        </xs:key>
        <xs:keyref name="NhanVien_HoaDonNhapKeyref" refer="NhanVienKey">
            <xs:selector xpath="HoaDonNhap"/>
            <xs:field xpath="MaNV"/>
        </xs:keyref>
        <xs:keyref name="HangHoa_ChiTietNhapKeyref" refer="HangHoaKey">
            <xs:selector xpath="ChiTietNhap"/>
            <xs:field xpath="MaHH"/>
        </xs:keyref>
        <xs:keyref name="HoaDonNhap_ChiTietNhapKeyref" refer="HoaDonNhapKey">
            <xs:selector xpath="ChiTietNhap"/>
            <xs:field xpath="SoHD"/>
        </xs:keyref>
    </xs:element>
</xs:schema>

=== QuocHuyTruong/XML/TruongQuocHuy_KTlan2_61133757/QLNH.xml
<?xml version="1.0" encoding="UTF-8"?>

<?xml-stylesheet type="text/xsl" href="QLNH.xsl"?>
<QLNH xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="QLNH.xsd">
    <NhanVien>
        <MaNV>NV01</MaNV>
        <HoLot>Tran</HoLot>
        <Ten>Loi</Ten>
        <GioiTinh>Nam</GioiTinh>
    </NhanVien>
    <NhanVien>
        <MaNV>NV02</MaNV>
        <HoLot>Nguyen</HoLot>
        <Ten>An</Ten>
        <GioiTinh>Nam</GioiTinh>
    </NhanVien>
    <NhanVien>
        <MaNV>NV03</MaNV>
        <HoLot>Le</HoLot>
        <Ten>Hieu</Ten>
        <GioiTinh>Nam</GioiTinh>
    </NhanVien>
    <NhanVien>
        <MaNV>NV04</MaNV>
        <HoLot>Tran</HoLot>
        <Ten>Quynh</Ten>
        <GioiTinh>Nu</GioiTinh>
    </NhanVien>
    <NhanVien>
        <MaNV>NV05</MaNV>
        <HoLot>Phan</HoLot>
        <Ten>Trang</Ten>
        <GioiTinh>Nu</GioiTinh>
    </NhanVien>
    
    <HangHoa>
        <MaHH>H001</MaHH>
        <TenHH>Laptop</TenHH>
        <DonViTinh>Cai</DonViTinh>
        <TenNCC>Dell</TenNCC>
    </HangHoa>
    <HangHoa>
        <MaHH>H002</MaHH>
        <TenHH>But chi</TenHH>
        <DonViTinh>Chiec</DonViTinh>
        <TenNCC>Thien Long</TenNCC>
    </HangHoa>
    <HangHoa>
        <MaHH>H003</MaHH>
        <TenHH>Cam</TenHH>
        <DonViTinh>Thung</DonViTinh>
        <TenNCC>Thu Ha</TenNCC>
    </HangHoa>
    <HangHoa>
        <MaHH>H004</MaHH>
        <TenHH>Tao</TenHH>
        <DonViTinh>Kg</DonViTinh>
        <TenNCC>Phuong Nam</TenNCC>
    </HangHoa>
    <HangHoa>
        <MaHH>H005</MaHH>
        <TenHH>Xe may</TenHH>
        <DonViTinh>Chiec</DonViTinh>
        <TenNCC>Yamaha</TenNCC>
    </HangHoa>
    
    <HoaDonNhap>
        <SoHD>HD0001</SoHD>
        <NgayNhap>01/01/2020</NgayNhap>
        <MaNV>NV01</MaNV>
    </HoaDonNhap>
    <HoaDonNhap>
        <SoHD>HD0002</SoHD>
        <NgayNhap>02/01/2020</NgayNhap>
        <MaNV>NV02</MaNV>
    </HoaDonNhap>
    <HoaDonNhap>
        <SoHD>HD0003</SoHD>
        <NgayNhap>03/01/2021</NgayNhap>
        <MaNV>NV03</MaNV>
    </HoaDonNhap>
    <HoaDonNhap>
        <SoHD>HD0004</SoHD>
        <NgayNhap>04/01/2021</NgayNhap>
        <MaNV>NV04</MaNV>
    </HoaDonNhap>
    <HoaDonNhap>
        <SoHD>HD0005</SoHD>
        <NgayNhap>05/01/2021</NgayNhap>
        <MaNV>NV05</MaNV>
    </HoaDonNhap>
    
    <ChiTietNhap>
        <SoHD>HD0001</SoHD>
        <MaHH>H001</MaHH>
        <SoLuong>10</SoLuong>
        <DonGiaNhap>1000000</DonGiaNhap>
    </ChiTietNhap>
    <ChiTietNhap>
        <SoHD>HD0002</SoHD>
        <MaHH>H002</MaHH>
        <SoLuong>20</SoLuong>
        <DonGiaNhap>2000</DonGiaNhap>
    </ChiTietNhap>
    <ChiTietNhap>
        <SoHD>HD0003</SoHD>
        <MaHH>H003</MaHH>
        <SoLuong>30</SoLuong>
        <DonGiaNhap>50000</DonGiaNhap>
    </ChiTietNhap>
    <ChiTietNhap>
        <SoHD>HD0004</SoHD>
        <MaHH>H004</MaHH>
        <SoLuong>40</SoLuong>
        <DonGiaNhap>40000</DonGiaNhap>
    </ChiTietNhap>
    <ChiTietNhap>
        <SoHD>HD0005</SoHD>
        <MaHH>H005</MaHH>
        <SoLuong>50</SoLuong>
        <DonGiaNhap>40000000</DonGiaNhap>
    </ChiTietNhap>
</QLNH>
